# docker-compose
version: '3.7'
services:
services:
  app:
    env_file:
      - .env
    build: .
    command: sh -c "npm start -host"
    ports:
      - 4200:4200
      - '49153:49153'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks: 
      - expense
volumes:
  node_modules:

networks:
  expense:
    external: true
    name: ${NETWORK_NAME}